api_version: 0.1  # Unstable API

robot:
    default_config: [0.00, -1.3, 0.00, -2.87, 0.00, 2.00, 0.75, .0, .0]
    end_effector: right_gripper

    # These limits are taken from the Franka spec sheet (except for the finger
    # limits, which are made up).
    accel_limits: [15., 7.5, 10., 12.5, 15., 20., 20., 10., 10.]
    jerk_limits: [7500., 3750., 5000., 6250., 7500., 10000., 10000., 1000., 1000.]

world:
    obstacles:
        # Self collision representation
        - center: [.0, .0, .3]
          radius: .1
          visible: false
        - center: [.0, .0, .15]
          radius: .1
          visible: false

fabrics:
    integrator_type: displacement

    cspace_control:
        suppress: false
        params:
            p_gain: 8.
            d_gain: 5.
            weight: 100

    joint_limit_control:
        suppress: false
        params:
            force_x_length_scale: .025
            p_gain: 80.
            d_gain: 20.
            metric_x_length_scale: .1
            weight: 2400.
